from django.utils.translation import gettext_lazy as _


ISO_3166_CODES = [
    ('AF', _("Afghanistan")),
    ('AX', _("Aland Islands")),
    ('AL', _("Albania")),
    ('DZ', _("Algeria")),
    ('AS', _("American Samoa")),
    ('AD', _("Andorra")),
    ('AO', _("Angola")),
    ('AI', _("Anguilla")),
    ('AQ', _("Antarctica")),
    ('AG', _("Antigua And Barbuda")),
    ('AR', _("Argentina")),
    ('AM', _("Armenia")),
    ('AW', _("Aruba")),
    ('AU', _("Australia")),
    ('AT', _("Austria")),
    ('AZ', _("Azerbaijan")),
    ('BS', _("Bahamas")),
    ('BH', _("Bahrain")),
    ('BD', _("Bangladesh")),
    ('BB', _("Barbados")),
    ('BY', _("Belarus")),
    ('BE', _("Belgium")),
    ('BZ', _("Belize")),
    ('BJ', _("Benin")),
    ('BM', _("Bermuda")),
    ('BT', _("Bhutan")),
    ('BO', _("Bolivia, Plurinational State Of")),
    ('BQ', _("Bonaire, Saint Eustatius And Saba")),
    ('BA', _("Bosnia And Herzegovina")),
    ('BW', _("Botswana")),
    ('BV', _("Bouvet Island")),
    ('BR', _("Brazil")),
    ('IO', _("British Indian Ocean Territory")),
    ('BN', _("Brunei Darussalam")),
    ('BG', _("Bulgaria")),
    ('BF', _("Burkina Faso")),
    ('BI', _("Burundi")),
    ('KH', _("Cambodia")),
    ('CM', _("Cameroon")),
    ('CA', _("Canada")),
    ('CV', _("Cape Verde")),
    ('KY', _("Cayman Islands")),
    ('CF', _("Central African Republic")),
    ('TD', _("Chad")),
    ('CL', _("Chile")),
    ('CN', _("China")),
    ('CX', _("Christmas Island")),
    ('CC', _("Cocos (Keeling) Islands")),
    ('CO', _("Colombia")),
    ('KM', _("Comoros")),
    ('CG', _("Congo")),
    ('CD', _("Congo, The Democratic Republic Of The")),
    ('CK', _("Cook Islands")),
    ('CR', _("Costa Rica")),
    ('HR', _("Croatia")),
    ('CU', _("Cuba")),
    ('CW', _("Curacao")),
    ('CY', _("Cyprus")),
    ('CZ', _("Czech Republic")),
    ('DK', _("Denmark")),
    ('DJ', _("Djibouti")),
    ('DM', _("Dominica")),
    ('DO', _("Dominican Republic")),
    ('EC', _("Ecuador")),
    ('EG', _("Egypt")),
    ('SV', _("El Salvador")),
    ('GQ', _("Equatorial Guinea")),
    ('ER', _("Eritrea")),
    ('EE', _("Estonia")),
    ('ET', _("Ethiopia")),
    ('FK', _("Falkland Islands (Malvinas)")),
    ('FO', _("Faroe Islands")),
    ('FJ', _("Fiji")),
    ('FI', _("Finland")),
    ('FR', _("France")),
    ('GF', _("French Guiana")),
    ('PF', _("French Polynesia")),
    ('TF', _("French Southern Territories")),
    ('GA', _("Gabon")),
    ('GM', _("Gambia")),
    ('DE', _("Germany")),
    ('GH', _("Ghana")),
    ('GI', _("Gibraltar")),
    ('GR', _("Greece")),
    ('GL', _("Greenland")),
    ('GD', _("Grenada")),
    ('GP', _("Guadeloupe")),
    ('GU', _("Guam")),
    ('GT', _("Guatemala")),
    ('GG', _("Guernsey")),
    ('GN', _("Guinea")),
    ('GW', _("Guinea-Bissau")),
    ('GY', _("Guyana")),
    ('HT', _("Haiti")),
    ('HM', _("Heard Island and McDonald Islands")),
    ('VA', _("Holy See (Vatican City State)")),
    ('HN', _("Honduras")),
    ('HK', _("Hong Kong")),
    ('HU', _("Hungary")),
    ('IS', _("Iceland")),
    ('IN', _("India")),
    ('ID', _("Indonesia")),
    ('IR', _("Iran, Islamic Republic Of")),
    ('IQ', _("Iraq")),
    ('IE', _("Ireland")),
    ('IL', _("Israel")),
    ('IT', _("Italy")),
    ('CI', _("Ivory Coast")),
    ('JM', _("Jamaica")),
    ('JP', _("Japan")),
    ('JE', _("Jersey")),
    ('JO', _("Jordan")),
    ('KZ', _("Kazakhstan")),
    ('KE', _("Kenya")),
    ('KI', _("Kiribati")),
    ('KP', _("Korea, Democratic People's Republic Of")),
    ('KR', _("Korea, Republic Of")),
    ('KS', _("Kosovo")),
    ('KW', _("Kuwait")),
    ('KG', _("Kyrgyzstan")),
    ('LA', _("Lao People's Democratic Republic")),
    ('LV', _("Latvia")),
    ('LB', _("Lebanon")),
    ('LS', _("Lesotho")),
    ('LR', _("Liberia")),
    ('LY', _("Libyan Arab Jamahiriya")),
    ('LI', _("Liechtenstein")),
    ('LT', _("Lithuania")),
    ('LU', _("Luxembourg")),
    ('MO', _("Macao")),
    ('MK', _("Macedonia")),
    ('MG', _("Madagascar")),
    ('MW', _("Malawi")),
    ('MY', _("Malaysia")),
    ('MV', _("Maldives")),
    ('ML', _("Mali")),
    ('ML', _("Malta")),
    ('MH', _("Marshall Islands")),
    ('MQ', _("Martinique")),
    ('MR', _("Mauritania")),
    ('MU', _("Mauritius")),
    ('YT', _("Mayotte")),
    ('MX', _("Mexico")),
    ('FM', _("Micronesia")),
    ('MD', _("Moldova")),
    ('MC', _("Monaco")),
    ('MN', _("Mongolia")),
    ('ME', _("Montenegro")),
    ('MS', _("Montserrat")),
    ('MA', _("Morocco")),
    ('MZ', _("Mozambique")),
    ('MM', _("Myanmar")),
    ('NA', _("Namibia")),
    ('NR', _("Nauru")),
    ('NP', _("Nepal")),
    ('NL', _("Netherlands")),
    ('AN', _("Netherlands Antilles")),
    ('NC', _("New Caledonia")),
    ('NZ', _("New Zealand")),
    ('NI', _("Nicaragua")),
    ('NE', _("Niger")),
    ('NG', _("Nigeria")),
    ('NU', _("Niue")),
    ('NF', _("Norfolk Island")),
    ('MP', _("Northern Mariana Islands")),
    ('NO', _("Norway")),
    ('OM', _("Oman")),
    ('PK', _("Pakistan")),
    ('PW', _("Palau")),
    ('PS', _("Palestinian Territory, Occupied")),
    ('PA', _("Panama")),
    ('PG', _("Papua New Guinea")),
    ('PY', _("Paraguay")),
    ('PE', _("Peru")),
    ('PH', _("Philippines")),
    ('PN', _("Pitcairn")),
    ('PL', _("Poland")),
    ('PT', _("Portugal")),
    ('PR', _("Puerto Rico")),
    ('QA', _("Qatar")),
    ('RE', _("Reunion")),
    ('RO', _("Romania")),
    ('RU', _("Russian Federation")),
    ('RW', _("Rwanda")),
    ('BL', _("Saint Barthelemy")),
    ('SH', _("Saint Helena, Ascension & Tristan Da Cunha")),
    ('KN', _("Saint Kitts and Nevis")),
    ('LC', _("Saint Lucia")),
    ('MF', _("Saint Martin (French Part)")),
    ('PM', _("Saint Pierre and Miquelon")),
    ('VC', _("Saint Vincent And The Grenadines")),
    ('WS', _("Samoa")),
    ('SM', _("San Marino")),
    ('ST', _("Sao Tome And Principe")),
    ('SA', _("Saudi Arabia")),
    ('SN', _("Senegal")),
    ('RS', _("Serbia")),
    ('SC', _("Seychelles")),
    ('SL', _("Sierra Leone")),
    ('SG', _("Singapore")),
    ('SX', _("Sint Maarten (Dutch Part)")),
    ('SK', _("Slovakia")),
    ('SI', _("Slovenia")),
    ('SB', _("Solomon Islands")),
    ('SO', _("Somalia")),
    ('ZA', _("South Africa")),
    ('GS', _("South Georgia And The South Sandwich Islands")),
    ('ES', _("Spain")),
    ('LK', _("Sri Lanka")),
    ('SD', _("Sudan")),
    ('SR', _("Suriname")),
    ('SJ', _("Svalbard And Jan Mayen")),
    ('SZ', _("Swaziland")),
    ('SE', _("Sweden")),
    ('CH', _("Switzerland")),
    ('SY', _("Syrian Arab Republic")),
    ('TW', _("Taiwan")),
    ('TJ', _("Tajikistan")),
    ('TZ', _("Tanzania")),
    ('TH', _("Thailand")),
    ('TL', _("Timor-Leste")),
    ('TG', _("Togo")),
    ('TK', _("Tokelau")),
    ('TO', _("Tonga")),
    ('TT', _("Trinidad and Tobago")),
    ('TN', _("Tunisia")),
    ('TR', _("Turkey")),
    ('TM', _("Turkmenistan")),
    ('TC', _("Turks And Caicos Islands")),
    ('TV', _("Tuvalu")),
    ('UG', _("Uganda")),
    ('UA', _("Ukraine")),
    ('AE', _("United Arab Emirates")),
    ('GB', _("United Kingdom")),
    ('US', _("United States")),
    ('UM', _("United States Minor Outlying Islands")),
    ('UY', _("Uruguay")),
    ('UZ', _("Uzbekistan")),
    ('VU', _("Vanuatu")),
    ('VE', _("Venezuela, Bolivarian Republic Of")),
    ('VN', _("Viet Nam")),
    ('VG', _("Virgin Islands, British")),
    ('VI', _("Virgin Islands, U.S.")),
    ('WF', _("Wallis and Futuna")),
    ('EH', _("Western Sahara")),
    ('YE', _("Yemen")),
    ('ZM', _("Zambia")),
    ('ZW', _("Zimbabwe")), ]

POSTCODES_REGEX = {
    'AC': r'^[A-Z]{4}[0-9][A-Z]$',
    'AD': r'^AD[0-9]{3}$',
    'AF': r'^[0-9]{4}$',
    'AI': r'^AI-2640$',
    'AL': r'^[0-9]{4}$',
    'AM': r'^[0-9]{4}$',
    'AR': r'^([0-9]{4}|[A-Z][0-9]{4}[A-Z]{3})$',
    'AS': r'^[0-9]{5}(-[0-9]{4}|-[0-9]{6})?$',
    'AT': r'^[0-9]{4}$',
    'AU': r'^[0-9]{4}$',
    'AX': r'^[0-9]{5}$',
    'AZ': r'^AZ[0-9]{4}$',
    'BA': r'^[0-9]{5}$',
    'BB': r'^BB[0-9]{5}$',
    'BD': r'^[0-9]{4}$',
    'BE': r'^[0-9]{4}$',
    'BG': r'^[0-9]{4}$',
    'BH': r'^[0-9]{3,4}$',
    'BL': r'^[0-9]{5}$',
    'BM': r'^[A-Z]{2}([0-9]{2}|[A-Z]{2})',
    'BN': r'^[A-Z]{2}[0-9]{4}$',
    'BO': r'^[0-9]{4}$',
    'BR': r'^[0-9]{5}(-[0-9]{3})?$',
    'BT': r'^[0-9]{3}$',
    'BY': r'^[0-9]{6}$',
    'CA': r'^[A-Z][0-9][A-Z][0-9][A-Z][0-9]$',
    'CC': r'^[0-9]{4}$',
    'CH': r'^[0-9]{4}$',
    'CL': r'^([0-9]{7}|[0-9]{3}-[0-9]{4})$',
    'CN': r'^[0-9]{6}$',
    'CO': r'^[0-9]{6}$',
    'CR': r'^[0-9]{4,5}$',
    'CU': r'^[0-9]{5}$',
    'CV': r'^[0-9]{4}$',
    'CX': r'^[0-9]{4}$',
    'CY': r'^[0-9]{4}$',
    'CZ': r'^[0-9]{5}$',
    'DE': r'^[0-9]{5}$',
    'DK': r'^[0-9]{4}$',
    'DO': r'^[0-9]{5}$',
    'DZ': r'^[0-9]{5}$',
    'EC': r'^EC[0-9]{6}$',
    'EE': r'^[0-9]{5}$',
    'EG': r'^[0-9]{5}$',
    'ES': r'^[0-9]{5}$',
    'ET': r'^[0-9]{4}$',
    'FI': r'^[0-9]{5}$',
    'FK': r'^[A-Z]{4}[0-9][A-Z]{2}$',
    'FM': r'^[0-9]{5}(-[0-9]{4})?$',
    'FO': r'^[0-9]{3}$',
    'FR': r'^[0-9]{5}$',
    'GA': r'^[0-9]{2}.*[0-9]{2}$',
    'GB': r'^[A-Z][A-Z0-9]{1,3}[0-9][A-Z]{2}$',
    'GE': r'^[0-9]{4}$',
    'GF': r'^[0-9]{5}$',
    'GG': r'^([A-Z]{2}[0-9]{2,3}[A-Z]{2})$',
    'GI': r'^GX111AA$',
    'GL': r'^[0-9]{4}$',
    'GP': r'^[0-9]{5}$',
    'GR': r'^[0-9]{5}$',
    'GS': r'^SIQQ1ZZ$',
    'GT': r'^[0-9]{5}$',
    'GU': r'^[0-9]{5}$',
    'GW': r'^[0-9]{4}$',
    'HM': r'^[0-9]{4}$',
    'HN': r'^[0-9]{5}$',
    'HR': r'^[0-9]{5}$',
    'HT': r'^[0-9]{4}$',
    'HU': r'^[0-9]{4}$',
    'ID': r'^[0-9]{5}$',
    'IL': r'^([0-9]{5}|[0-9]{7})$',
    'IM': r'^IM[0-9]{2,3}[A-Z]{2}$$',
    'IN': r'^[0-9]{6}$',
    'IO': r'^[A-Z]{4}[0-9][A-Z]{2}$',
    'IQ': r'^[0-9]{5}$',
    'IR': r'^[0-9]{5}-[0-9]{5}$',
    'IS': r'^[0-9]{3}$',
    'IT': r'^[0-9]{5}$',
    'JE': r'^JE[0-9]{2}[A-Z]{2}$',
    'JM': r'^JM[A-Z]{3}[0-9]{2}$',
    'JO': r'^[0-9]{5}$',
    'JP': r'^[0-9]{3}-?[0-9]{4}$',
    'KE': r'^[0-9]{5}$',
    'KG': r'^[0-9]{6}$',
    'KH': r'^[0-9]{5}$',
    'KR': r'^[0-9]{5}$',
    'KY': r'^KY[0-9]-[0-9]{4}$',
    'KZ': r'^[0-9]{6}$',
    'LA': r'^[0-9]{5}$',
    'LB': r'^[0-9]{8}$',
    'LI': r'^[0-9]{4}$',
    'LK': r'^[0-9]{5}$',
    'LR': r'^[0-9]{4}$',
    'LS': r'^[0-9]{3}$',
    'LT': r'^(LT-)?[0-9]{5}$',
    'LU': r'^[0-9]{4}$',
    'LV': r'^LV-[0-9]{4}$',
    'LY': r'^[0-9]{5}$',
    'MA': r'^[0-9]{5}$',
    'MC': r'^980[0-9]{2}$',
    'MD': r'^MD-?[0-9]{4}$',
    'ME': r'^[0-9]{5}$',
    'MF': r'^[0-9]{5}$',
    'MG': r'^[0-9]{3}$',
    'MH': r'^[0-9]{5}$',
    'MK': r'^[0-9]{4}$',
    'MM': r'^[0-9]{5}$',
    'MN': r'^[0-9]{5}$',
    'MP': r'^[0-9]{5}$',
    'MQ': r'^[0-9]{5}$',
    'MT': r'^[A-Z]{3}[0-9]{4}$',
    'MV': r'^[0-9]{4,5}$',
    'MX': r'^[0-9]{5}$',
    'MY': r'^[0-9]{5}$',
    'MZ': r'^[0-9]{4}$',
    'NA': r'^[0-9]{5}$',
    'NC': r'^[0-9]{5}$',
    'NE': r'^[0-9]{4}$',
    'NF': r'^[0-9]{4}$',
    'NG': r'^[0-9]{6}$',
    'NI': r'^[0-9]{5}$',
    'NL': r'^[0-9]{4}[A-Z]{2}$',
    'NO': r'^[0-9]{4}$',
    'NP': r'^[0-9]{5}$',
    'NZ': r'^[0-9]{4}$',
    'OM': r'^[0-9]{3}$',
    'PA': r'^[0-9]{6}$',
    'PE': r'^[0-9]{5}$',
    'PF': r'^[0-9]{5}$',
    'PG': r'^[0-9]{3}$',
    'PH': r'^[0-9]{4}$',
    'PK': r'^[0-9]{5}$',
    'PL': r'^[0-9]{2}-?[0-9]{3}$',
    'PM': r'^[0-9]{5}$',
    'PN': r'^[A-Z]{4}[0-9][A-Z]{2}$',
    'PR': r'^[0-9]{5}$',
    'PT': r'^[0-9]{4}(-?[0-9]{3})?$',
    'PW': r'^[0-9]{5}$',
    'PY': r'^[0-9]{4}$',
    'RE': r'^[0-9]{5}$',
    'RO': r'^[0-9]{6}$',
    'RS': r'^[0-9]{5}$',
    'RU': r'^[0-9]{6}$',
    'SA': r'^[0-9]{5}$',
    'SD': r'^[0-9]{5}$',
    'SE': r'^[0-9]{5}$',
    'SG': r'^([0-9]{2}|[0-9]{4}|[0-9]{6})$',
    'SH': r'^(STHL1ZZ|TDCU1ZZ)$',
    'SI': r'^(SI-)?[0-9]{4}$',
    'SK': r'^[0-9]{5}$',
    'SM': r'^[0-9]{5}$',
    'SN': r'^[0-9]{5}$',
    'SV': r'^01101$',
    'SZ': r'^[A-Z][0-9]{3}$',
    'TC': r'^TKCA1ZZ$',
    'TD': r'^[0-9]{5}$',
    'TH': r'^[0-9]{5}$',
    'TJ': r'^[0-9]{6}$',
    'TM': r'^[0-9]{6}$',
    'TN': r'^[0-9]{4}$',
    'TR': r'^[0-9]{5}$',
    'TT': r'^[0-9]{6}$',
    'TW': r'^([0-9]{3}|[0-9]{5})$',
    'UA': r'^[0-9]{5}$',
    'US': r'^[0-9]{5}(-[0-9]{4}|-[0-9]{6})?$',
    'UY': r'^[0-9]{5}$',
    'UZ': r'^[0-9]{6}$',
    'VA': r'^00120$',
    'VC': r'^VC[0-9]{4}',
    'VE': r'^[0-9]{4}[A-Z]?$',
    'VG': r'^VG[0-9]{4}$',
    'VI': r'^[0-9]{5}$',
    'VN': r'^[0-9]{6}$',
    'WF': r'^[0-9]{5}$',
    'XK': r'^[0-9]{5}$',
    'YT': r'^[0-9]{5}$',
    'ZA': r'^[0-9]{4}$',
    'ZM': r'^[0-9]{5}$',
}