# Generated by Django 4.0.7 on 2022-09-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('config', models.CharField(choices=[('APP_NAME', 'APPLICATION NAME')], max_length=25, primary_key=True, serialize=False, verbose_name='Configuration Name')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'System Configuration',
            },
        ),
    ]
